# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/melff/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

before_build:
  - cp ..\travis-tool.sh .\travis-tool.sh
  - cp travis-tool.sh.cmd pkg\travis-tool.sh.cmd
  - cd pkg
  - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"
  
build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install knitr rmarkdown evaluate digest formatR highr markdown stringr yaml
  
test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: 'pkg\*.Rcheck\**\*.log'
    name: Logs

  - path: 'pkg\*.Rcheck\**\*.out'
    name: Logs

  - path: 'pkg\*.Rcheck\**\*.fail'
    name: Logs

  - path: 'pkg\*.Rcheck\**\*.Rout'
    name: Logs

  - path: 'pkg\*_*.tar.gz'
    name: Bits

  - path: 'pkg\*_*.zip'
    name: Bits

version: 0.99.5-{build}

branches:
  only:
  - master

notifications:
  - provider: Email
    to: memisc@elff.eu
    on_build_success: change
    on_build_failure: true
